
# This tmux.conf is for laptop or notebooks if you need for Desktop read tmux.md on Miunidad.

# we change default `Control+b` to `Meta+m`, but
# if you do not want just comment the next line
set -g prefix  M-m            #M-n(this is free too) 

# for copy in vi mode
setw -g mode-keys vi

# new version of tmux has bind-key * to open floating panes.
# but to resize the floating panes you have to enable mouse.
# Thats wy we create 2 keybinds to enable and disable mouse:
# To eneable mouse, use <Prefix> + 1
bind-key 1 set -g mouse on
# To disable mouse, use <Prefix> + 2
bind-key 2 set -g mouse off

# Refresh status bar every 60 seconds
set -g status-interval 60
set -g status-right "Batt: #(status_batte.sh) | %Y-%m-%d %H:%M"

# Set the term color proplerly
set -g default-terminal "$TERM"
set -as terminal-features ",$TERM:RGB"

# set the staus style
set -g status-style fg=white,bg=black

# set colors fo the active window
setw -g window-status-current-style fg=white,bold,bg=blue


