
# This tmux.conf is for laptop or notebooks if you need for Desktop read tmux.md on Miunidad.

# this is for change keybingding
set -g prefix  M-m            #M-n(this is free too) 

# for copy in vi mode
setw -g mode-keys vi

# Refresh status bar every 60 seconds
set -g status-interval 60
set -g status-right "Batt: #(status_batte.sh) | %Y-%m-%d %H:%M"

# Set the term color proplerly
set -g default-terminal "$TERM"
set -as terminal-features ",$TERM:RGB"

# set the staus style
set -g status-style fg=white,bg=black

# set colors fo the active window
setw -g window-status-current-style fg=white,bold,bg=blue

